---
# roles/unifi/tasks/unifi_install.yml: Installation 'unifi' role. Called by main.yml
# Load a variable file based on the OS type (Unifi only installs on Debian!), or a default if not found.

- debug: var=ansible_os_family

- name: Install Unifi
  package: 
    name: "{{ unifi_package }}"
    state: latest
  # Implied enable service
  notify: "Start Unifi Service"
