---
# Purpose: Handlers for Unifi services
# Last Updated: 2018.06.11
# Notes:


- block:

    - name: "Start Unifi Service"
      service:
       name: "{{ unifi_service }}"
       state: started
       enabled: yes

    - name: "Restart Unifi Service"
      service:
       name: "{{ unifi_service }}"
       state: restarted

  become: true